spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: clean-archi-app
  security:
    oauth2:
      enabled: false

server:
  port: 9095

logging:
  level:
    root: INFO
    com.example: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info

